/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class www_jin_com_jin_text_MainActivity */

#ifndef _Included_www_jin_com_jin_text_MainActivity
#define _Included_www_jin_com_jin_text_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     www_jin_com_jin_text_MainActivity
 * Method:    TextJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_www_jin_com_jin_1text_MainActivity_TextJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
